name: little_heroes
description: A fun RPG game
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  flame: ^1.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  nes_ui: ^0.5.0
  provider: ^6.0.5

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
